import type { Pack, Question, Card, User, DailyChallenge } from './types';

export const PACKS: Pack[] = [
  {
    id: 'pack_classiques',
    name: 'Classiques Absolus',
    description: 'Les punchlines incontournables du rap français',
    emoji: '🎤',
    totalQuestions: 20,
    access: 'free',
    color: '#7C3AED',
    category: 'Classiques',
  },
  {
    id: 'pack_legendes',
    name: 'Légendes 90s/2000s',
    description: "L'âge d'or du rap français",
    emoji: '👑',
    totalQuestions: 20,
    access: 'premium',
    color: '#F59E0B',
    category: 'Histoire',
  },
  {
    id: 'pack_nouvelle_ecole',
    name: 'Nouvelle École',
    description: "Les artistes qui font le rap français aujourd'hui",
    emoji: '🔥',
    totalQuestions: 20,
    access: 'grind',
    grindRequirements: {
      victories: 20,
      correctAnswers: 150,
    },
    color: '#EF4444',
    category: 'Tendances',
  },
  {
    id: 'pack_plume',
    name: 'Plume & Mélodie',
    description: 'Les textes les plus poétiques du rap français',
    emoji: '✨',
    totalQuestions: 20,
    access: 'premium',
    color: '#3B82F6',
    category: 'Poésie',
  },
  {
    id: 'pack_pnl',
    name: 'Spécial PNL',
    description: "Dédié entièrement au duo de l'Amorce",
    emoji: '🌙',
    totalQuestions: 20,
    access: 'premium',
    color: '#6366F1',
    category: 'Artiste',
  },
];

export const QUESTIONS: Question[] = [
  {
    id: 'q1',
    packId: 'pack_classiques',
    type: 'whoSaidThis',
    questionText: '"Je suis un caméléon, un caméléon"',
    correctAnswer: 'Booba',
    choices: ['Booba', 'Rohff', 'Kaaris', 'SCH'],
    artistName: 'Booba',
    sourceTrack: 'Caméléon',
    difficulty: 1,
  },
  {
    id: 'q2',
    packId: 'pack_classiques',
    type: 'completePunchline',
    questionText: '"J\'suis pas le meilleur, j\'suis le ___ qui reste"',
    correctAnswer: 'seul',
    choices: ['seul', 'dernier', 'premier', 'vrai'],
    missingWord: 'seul',
    artistName: 'Nekfeu',
    sourceTrack: 'Nique le monde',
    difficulty: 2,
  },
  {
    id: 'q3',
    packId: 'pack_classiques',
    type: 'whoSaidThis',
    questionText: '"On n\'est pas des anges, mais pas des démons"',
    correctAnswer: 'PNL',
    choices: ['PNL', 'Damso', 'Ninho', 'Jul'],
    artistName: 'PNL',
    sourceTrack: "Jusqu'au dernier gramme",
    difficulty: 1,
  },
  {
    id: 'q4',
    packId: 'pack_classiques',
    type: 'whoSaidThis',
    questionText: '"Ma vie est un roman, j\'en suis l\'auteur"',
    correctAnswer: 'Nekfeu',
    choices: ['Nekfeu', 'Lomepal', 'Orelsan', 'Vald'],
    artistName: 'Nekfeu',
    difficulty: 2,
  },
  {
    id: 'q5',
    packId: 'pack_classiques',
    type: 'completePunchline',
    questionText: '"Je viens du ___, pas du paradis"',
    correctAnswer: 'bitume',
    choices: ['bitume', 'quartier', 'béton', 'ghetto'],
    missingWord: 'bitume',
    artistName: 'Kaaris',
    difficulty: 1,
  },
  {
    id: 'q6',
    packId: 'pack_classiques',
    type: 'whoSaidThis',
    questionText: '"L\'argent n\'a pas d\'odeur mais ça sent bon"',
    correctAnswer: 'Booba',
    choices: ['Booba', 'Rohff', 'La Fouine', 'Alonzo'],
    artistName: 'Booba',
    difficulty: 1,
  },
  {
    id: 'q7',
    packId: 'pack_classiques',
    type: 'whoSaidThis',
    questionText: '"Je suis de la génération sacrifiée"',
    correctAnswer: 'Orelsan',
    choices: ['Orelsan', 'Lomepal', 'Vald', 'Therapie Taxi'],
    artistName: 'Orelsan',
    difficulty: 2,
  },
  {
    id: 'q8',
    packId: 'pack_classiques',
    type: 'completePunchline',
    questionText: '"La vie c\'est pas un long ___ tranquille"',
    correctAnswer: 'fleuve',
    choices: ['fleuve', 'chemin', 'voyage', 'rêve'],
    missingWord: 'fleuve',
    artistName: 'Oxmo Puccino',
    difficulty: 3,
  },
  {
    id: 'q9',
    packId: 'pack_classiques',
    type: 'whoSaidThis',
    questionText: '"Je rap pour les invisibles"',
    correctAnswer: 'Disiz',
    choices: ['Disiz', 'Médine', 'Hamza', 'Freeze Corleone'],
    artistName: 'Disiz',
    difficulty: 3,
  },
  {
    id: 'q10',
    packId: 'pack_classiques',
    type: 'completePunchline',
    questionText: '"On est des ___, pas des saints"',
    correctAnswer: 'guerriers',
    choices: ['guerriers', 'soldats', 'frères', 'fous'],
    missingWord: 'guerriers',
    difficulty: 2,
  },
];

export const CARDS: Card[] = [
  {
    id: 'card_booba',
    artistName: 'Booba',
    packId: 'pack_classiques',
    rarity: 'legendaire',
    description: 'Le Duc de Boulogne, figure incontournable du rap français',
    stats: { flow: 95, texte: 90, impact: 98 },
  },
  {
    id: 'card_nekfeu',
    artistName: 'Nekfeu',
    packId: 'pack_classiques',
    rarity: 'epique',
    description: 'Poète du bitume, membre de S-Crew',
    stats: { flow: 88, texte: 97, impact: 85 },
  },
  {
    id: 'card_orelsan',
    artistName: 'Orelsan',
    packId: 'pack_classiques',
    rarity: 'epique',
    description: "Victoire de la musique, voix d'une génération",
    stats: { flow: 82, texte: 98, impact: 90 },
  },
  {
    id: 'card_pnl',
    artistName: 'PNL',
    packId: 'pack_pnl',
    rarity: 'legendaire',
    description: "Le duo mystérieux de l'Amorce",
    stats: { flow: 92, texte: 95, impact: 96 },
  },
  {
    id: 'card_sch',
    artistName: 'SCH',
    packId: 'pack_classiques',
    rarity: 'rare',
    description: 'Le Marseillais au style trap unique',
    stats: { flow: 90, texte: 88, impact: 87 },
  },
  {
    id: 'card_ninho',
    artistName: 'Ninho',
    packId: 'pack_nouvelle_ecole',
    rarity: 'epique',
    description: 'Recordman de streams, le roi du drill français',
    stats: { flow: 94, texte: 80, impact: 92 },
  },
  {
    id: 'card_damso',
    artistName: 'Damso',
    packId: 'pack_classiques',
    rarity: 'legendaire',
    description: "Plume d'or du rap belge",
    stats: { flow: 89, texte: 99, impact: 91 },
  },
  {
    id: 'card_kaaris',
    artistName: 'Kaaris',
    packId: 'pack_classiques',
    rarity: 'rare',
    description: 'La voix de Sevran, punchlines redoutables',
    stats: { flow: 86, texte: 85, impact: 89 },
  },
];

export const INITIAL_USER: User = {
  id: 'user_1',
  username: 'RapKing',
  level: 7,
  xp: 3200,
  xpToNextLevel: 4000,
  coins: 850,
  streak: 5,
  victories: 12,
  correctAnswers: 89,
  totalAnswers: 120,
  collectedCardIds: ['card_sch', 'card_kaaris'],
  unlockedPackIds: ['pack_classiques'],
  isPremium: false,
};

export const DAILY_CHALLENGE: DailyChallenge = {
  id: 'daily_001',
  date: new Date().toISOString().split('T')[0],
  packId: 'pack_classiques',
  questionIds: ['q1', 'q2', 'q3', 'q4', 'q5'],
  reward: {
    coins: 100,
    xp: 200,
  },
};
